[0m17:23:37.996676 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D4A725D30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D4A725880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D4A725850>]}


============================== 17:23:38.011711 | 2c36ca2d-5b56-45da-b949-6d108fd03c94 ==============================
[0m17:23:38.011711 [info ] [MainThread]: Running with dbt=1.9.3
[0m17:23:38.011711 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\DÃ¡vidDobos\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run --model b_astro', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:23:38.011711 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\DÃ¡vidDobos\szakdoga\.venv\Scripts\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:23:38.011711 [debug] [MainThread]: Command `dbt run` failed at 17:23:38.011711 after 0.26 seconds
[0m17:23:38.011711 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D4A50E0C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D49CB8110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D49CB97F0>]}
[0m17:23:38.011711 [debug] [MainThread]: Flushing usage events
[0m17:23:38.499962 [debug] [MainThread]: An error was encountered while trying to flush usage events
